# Generated by Django 5.2.7 on 2025-10-11 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monday', models.FloatField(default=0)),
                ('Tuesday', models.FloatField(default=0)),
                ('Wednesday', models.FloatField(default=0)),
                ('Thursday', models.FloatField(default=0)),
                ('Friday', models.FloatField(default=0)),
                ('Saturday', models.FloatField(default=0)),
                ('Sunday', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
